Added Milk Tossing Trigger
Joel-Paul/Achievements-Addon pull request #7
Opened 2023-09-10 22:27 UTC by socklessthing

EventType MILK_TOSSED and EventDispatcher onMilkTossed()

2023-09-10 23:51 UTC, Joel-Paul requested changes
Looks good! Could you please move the `onMilkTossed` method to the existing `VillagerEntityMixin` class?

2023-09-10 23:51 UTC, Joel-Paul commented on src/main/java/issame/achievements_core/mixin/MilkTossMixin.java
> +    @Inject(method = "checkForLooseMilk",
Change method to `checkForLooseMilk()V`.
Just want to be certain we're injecting into the right place

2023-09-11 00:13 UTC, socklessthing commented
merged the two mixin classes :)

2023-09-11 00:28 UTC, Joel-Paul approved these changes

2023-09-11 00:28 UTC, merged